# Generated by Django 5.2.4 on 2025-08-13 03:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_comment_options_comment_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='postimage',
            options={'ordering': ['created_at'], 'verbose_name': 'Imagen del post', 'verbose_name_plural': 'Imágenes del post'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Puntuación', 'verbose_name_plural': 'Puntuaciones'},
        ),
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['approved'], name='post_commen_approve_829001_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug'], name='post_post_slug_010eca_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author'], name='post_post_author__0be58b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category'], name='post_post_categor_4c7296_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at'], name='post_post_created_0713d7_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['approved_post'], name='post_post_approve_88a911_idx'),
        ),
    ]
