# Generated by Django 5.2.4 on 2025-08-14 20:10

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_alias_alter_user_avatar_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user/default/default-avatar.png', upload_to=apps.user.models.get_avatar_filename),
        ),
    ]
